### ISSUE TITLE
"text_property" not working

### ISSUE THREAD

**Issue by RomainOdeval** [Chris53897/select2entity-bundle#1]
Hi Chris,

I know this fork is used mostly for your company but is it possible to insert this fix ? 
It will be great !

Thank you,

https://github.com/tetranz/select2entity-bundle/pull/181/files

**Comment by Chris53897** [comment]
Hi @RomainOdeval 
sorry i just noticed this issue.
I did merge your changes in this branch. (But i did not test it)
https://github.com/Chris53897/select2entity-bundle/tree/feature/php-8.0

**Comment by RomainOdeval** [comment]
Thank you, i close it !
